### ISSUE TITLE
캡스톤디자인 최종평가 자료 업로드

### ISSUE THREAD

**Issue by cpj509** [kookmin-sw/2019-cap1-2019_14#14]
포스터는 업로드 완료.

수행 결과 보고서 및 발표 자료 업로드 예정.

**Comment by cpj509** [comment]
master branch에 각 branch 항목들도 병합 예정.

**Comment by tomJeongJunLee** [comment]
-최종 수행계획서 작성 및 수정 작업중 마무리 후 깃에 업로드 
-시연영상 찍을 것
-최종발표 자료 만들 것

**Comment by donghyuk129** [comment]
최종보고서 작성 후 업로드 완료
시연영상 촬영 후 업로드 완료
최종발표 자료 제작 후 업로드 완료
포스터 파일 최종발표 폴더로 이전
